name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
      - develop

jobs:
  job_nanoS_build_debug:
    name: Build debug app for NanoS
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          make DEBUG=1
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: oxen-app-nanoS-debug
          path: bin
          if-no-files-found: error

  job_nanoX_build_debug:
    name: Build debug app for NanoX
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          make DEBUG=1 BOLOS_SDK=$NANOX_SDK
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: oxen-app-nanoX-debug
          path: bin
          if-no-files-found: error

  job_nanoSP_build_debug:
    name: Build debug app for Nano S Plus
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          make DEBUG=1 BOLOS_SDK=$NANOSP_SDK
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: oxen-app-nanoSP-debug
          path: bin
          if-no-files-found: error

  job_scan_build:
    name: Clang Static Analyzer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build
          path: scan-build

  job_test:
    name: Test
    needs: job_nanoS_build_debug
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: oxen-app-nanoS-debug
          path: bin

      - name: Run test
        run: |
          nohup bash -c "python /speculos/speculos.py bin/app.elf --seed \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about\" --apdu-port 9999 --api-port 5000 --display headless" > speculos.log 2<&1 &
          pip install pytest
          pytest
      - name: Upload Speculos log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-log
          path: speculos.log
